name: Development docs CI

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - tests/**

jobs:
  docs-test:
    if: github.ref != 'refs/heads/main'
    uses: arup-group/actions-city-modelling-lab/.github/workflows/docs-deploy.yml@main
    with:
      deploy_type: test
      notebook_kernel: genet

  docs-update-latest:
    permissions:
      contents: write
    if: github.ref == 'refs/heads/main'
    uses: arup-group/actions-city-modelling-lab/.github/workflows/docs-deploy.yml@main
    with:
      deploy_type: update_latest
      notebook_kernel: genet

  slack-notify-ci-failure:
    needs: [docs-test, docs-update-latest]
    if: always() && contains(needs.*.result, 'failure')
    uses: arup-group/actions-city-modelling-lab/.github/workflows/slack-notify.yml@main
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    with:
      result: 'failure'
      channel: genet-feed
      message: Docs Build